version: "2"

run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asciicheck
    - bodyclose
    - copyloopvar
    - dupl
    - durationcheck
    - errname
    - errorlint
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - lll
    - nakedret
    - nestif
    - nilerr
    - nolintlint
    - unconvert
    - unparam
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
    govet:
      disable:
        - fieldalignment
    funlen:
      lines: 80
      statements: 60
      ignore-comments: true
    lll:
      line-length: 140
    nakedret:
      max-func-lines: 0
