repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: go-build
        name: go build
        entry: mise exec -- go build ./...
        language: system
        pass_filenames: false

      - id: go-test
        name: go test
        entry: mise exec -- go test ./...
        language: system
        pass_filenames: false

      - id: golangci-lint
        name: golangci-lint
        entry: mise exec -- golangci-lint run
        language: system
        pass_filenames: false
