version: 2
jobs:
  build:
    docker:
      - image: golang:1.11.4
    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: dep ensure
      - run: go build